### ISSUE TITLE
Android studio解决gradle同步失败的相关问题 - DiscreteTom's Blog

### ISSUE THREAD

**Issue by DiscreteTom** [DiscreteTom/discretetom.github.io#1]
https://discretetom.github.io/2018/07/08/Android-Studio%E8%A7%A3%E5%86%B3Gradle%E5%90%8C%E6%AD%A5%E5%A4%B1%E8%B4%A5%E7%9A%84%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98/ 

 blog

**Comment by whitecambur** [comment]
很有帮助
