### ISSUE TITLE
bluetooth-notes.md的“使用 SDP 动态分配端口”部分demo不可用

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [DiscreteTom/discretetom.github.io#16]
- bluetooth中应该是没有get_available_port方法的
- `print "listening on port %d" % port`这种代码会报错`SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?`

**Comment by DiscreteTom** [comment]
博客里面的那段代码来自：https://people.csail.mit.edu/albert/bluez-intro/x290.html

年代比较久远，可能存在不准确的地方

不过看起来`get_available_port`方法的底层实现作为一个隐藏函数在pybuez里面还能用，详见

https://github.com/pybluez/pybluez/blob/82cbba8a1ebd4c1e3442dfafd8581d58c50fa39e/bluetooth/bluez.py#L152

可以参考这里自行实现`get_available_port`：

https://github.com/pybluez/pybluez/blob/82cbba8a1ebd4c1e3442dfafd8581d58c50fa39e/bluetooth/bluez.py#L193-L199

至于`print`的问题，由于年代原因原文看起来使用的是python 2的语法，在Python3里面报错是正常的。

建议参考pybluez官方文档编写代码，此博客仅用于形成感性认知

**Comment by lolPlatinumPlayer** [comment]
> 博客里面的那段代码来自：https://people.csail.mit.edu/albert/bluez-intro/x290.html
> 
> 年代比较久远，可能存在不准确的地方
> 
> 不过看起来`get_available_port`方法的底层实现作为一个隐藏函数在pybuez里面还能用，详见
> 
> https://github.com/pybluez/pybluez/blob/82cbba8a1ebd4c1e3442dfafd8581d58c50fa39e/bluetooth/bluez.py#L152
> 
> 可以参考这里自行实现`get_available_port`：
> 
> https://github.com/pybluez/pybluez/blob/82cbba8a1ebd4c1e3442dfafd8581d58c50fa39e/bluetooth/bluez.py#L193-L199
> 
> 至于`print`的问题，由于年代原因原文看起来使用的是python 2的语法，在Python3里面报错是正常的。
> 
> 建议参考pybluez官方文档编写代码，此博客仅用于形成感性认知

😄感谢作者指导，茅塞顿开
